name = "Bear Berry"
license = "MIT"
licenselink = "https://github.com/Pagliacii/hugo-bearberry/blob/main/LICENSE"
description = "A lightweight Hugo theme based on Hugo Bear Cub."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/Pagliacii/hugo-bearberry"

# If you have a running demo of the theme.
demosite = "https://pagliacii.github.io/hugo-bearberry"

tags = ["blog", "responsive", "minimal", "personal", "dark", "multilingual"]
features = ["favicon", "seo", "rss", "social cards"]

# If the theme has a single author
[author]
    name = "Jason Huang"
    homepage = "https://github.com/Pagliacii"

# If porting an existing theme
[original]
    author = "Caio Lenth"
    homepage = "https://lente.dev"
    repo = "https://github.com/clente/hugo-bearcub"

# Hugo versions the theme supports
[module]
  [module.hugoVersion]
    min = "0.90"
